### ISSUE TITLE
Requires an allocator

### ISSUE THREAD

**Issue by nils-van-zuijlen** [D1plo1d/tiny-artnet#1]
When in a no_std context, it is really common to have no allocator, but this crate requires `tiny-artnet-bytes-no-atomic` which requires having an allocator.

It would be nice if that was not the case, or at least documented.

**Comment by nils-van-zuijlen** [comment]
Also, I could not find your fork of `bytes`, and so cannot help with that.

**Comment by nils-van-zuijlen** [comment]
I managed to get it working by modifying the code retrieved from crates.io, I would really like to contribute back my changes so that a wider audience can enjoy them.

**Comment by pixelprizm** [comment]
Hey @nils-van-zuijlen, I am having the same issue you are - would like to use tiny-artnet without an allocator (on RP2040 (Pi Pico W)).  Can you share what you changed to get it to work?  Doesn't have to be a polished PR

**Comment by nils-van-zuijlen** [comment]
In `tiny-artnet`, `Cargo.toml`:
- Remove "alloc" from "nom" features
- Use path to specify "tiny-artnet-bytes-no-atomic" dependency
```toml
[dependencies]
nom = { version = "7.1.1", default-features = false, features = [] }
tiny-artnet-bytes-no-atomic = { version = "1.2.2", path = "../tiny-artnet-bytes-no-atomic", default-features = false }
```

In `tiny-artnet-bytes-no-atomic`:
To get this code, use `cargo vendor`, it will be downloaded in the `vendor` folder. You may follow the steps echoed by cargo and edit it there, or copy it to another folder.
- `Cargo.toml`
  - Add feature `alloc`
    ```toml
    [features]
    default = ["std", "alloc"]
    std = []
    alloc = []
    ```
- `src/lib.rs`
  - Place the feature flag on the `extern crate alloc`
    ```rust
    #[cfg(feature = "alloc")]
    extern crate alloc;
    ```
- `src/buf/buf_impl.rs`
  - Place the feature flag on the `use alloc` and `impl<T: Buf + ?Sized> Buf for Box<T>`
- `src/buf/buf_mut.rs`
  - Place the feature flag on the `use alloc`, `impl<T: Buf + ?Sized> Buf for Box<T>` and `unsafe impl BufMut for Vec<u8>`
- `src/buf/mod.rs`
  - Place the feature flag on the `mod vec_deque;`
    ```rust
    mod uninit_slice;
    #[cfg(feature = "alloc")]
    mod vec_deque;
    #[cfg(feature = "std")]
    mod writer;
    ```
